language: python

python:
  - "3.6"

services:
  - docker

script:
  - make test

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
    make publish;
    fi
